#!/bin/sh
#
# redis - this script starts and stops the redis daemon
#
# chkconfig:   - 85 15 
# description:  redis is a database fast \
#              
# processname: redis
# config:      /usr/local/redis/etc/redis.conf
# pidfile:     /var/run/redis.pid
 
# Source function library.
. /etc/rc.d/init.d/functions
 
# Source networking configuration.
. /etc/sysconfig/network
 
# Check that networking is up.
[ "$NETWORKING" = "no" ] && exit 0
 
redis="/usr/local/redis/bin/redis-server"
prog=$(basename $redis)
pid_file="/var/run/redis.pid" 
redis_CONF_FILE="/usr/local/redis/etc/redis.conf"
 
 
lockfile=/var/lock/subsys/redis
 

 
start() {
    [ -x $redis ] || exit 5
    [ -f $redis_CONF_FILE ] || exit 6
    echo -n $"Starting $prog: "
    daemon $redis  $redis_CONF_FILE
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}
 
stop() {
    echo -n $"Stopping $prog: "
    PID=$(ps -ef |grep redis |grep -v 'grep' |awk '{print $2}')
    kill -9 $PID >/dev/null 2>&1
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    [ $retval -eq 0 ] && rm -f $pid_file
    return $retval
}
 
restart() {
    stop
    sleep 1
    start
}
 
reload() {
    stop
    sleep 1
    start
}
 
force_reload() {
    restart
}
 

 
rh_status() {
    status $prog
}
 
rh_status_q() {
    rh_status >/dev/null 2>&1
}
 
case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart|configtest)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
            ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload|configtest}"
        exit 2
esac
